### ISSUE TITLE
Add remote http commandline interface

### ISSUE THREAD

**Issue by kordano** [replikativ/datahike-server#48]
It would be helpful to have a babashka client in the commandline that can talk to the server via a simple api.

**Comment by TimoKramer** [comment]
https://github.com/lispyclouds/bblgum

**Comment by whilo** [comment]
Note that you can compile `datahike.cli` with https://github.com/replikativ/datahike-server-transactor included and invoke it also from Babashka comfortably since it can speak edn (and could speak fressian or transit as well). Even better would be to compile Datahike into babashka and have a version that can use Datahike in the same memory system without remote procedure calls. That way you could run queries from Babashka even against multiple databases on different servers and can also use Babashka functions in Datalog.
